package org.taller.moduloDeTransferencia.wscliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2025-06-11T22:47:23.205-03:00
 * Generated source version: 4.0.0
 *
 */
@WebServiceClient(name = "BancoClienteService",
                  wsdlLocation = "http://localhost:8080/BancoClienteMock/BancoClienteService?wsdl",
                  targetNamespace = "http://ws.bancoClienteMock.taller.org/")
public class BancoClienteService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.bancoClienteMock.taller.org/", "BancoClienteService");
    public final static QName BancoClientePort = new QName("http://ws.bancoClienteMock.taller.org/", "BancoClientePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/BancoClienteMock/BancoClienteService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BancoClienteService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/BancoClienteMock/BancoClienteService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BancoClienteService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BancoClienteService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BancoClienteService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BancoClienteService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BancoClienteService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BancoClienteService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns BancoClienteService
     */
    @WebEndpoint(name = "BancoClientePort")
    public BancoClienteService getBancoClientePort() {
        return super.getPort(BancoClientePort, BancoClienteService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BancoClienteService
     */
    @WebEndpoint(name = "BancoClientePort")
    public BancoClienteService getBancoClientePort(WebServiceFeature... features) {
        return super.getPort(BancoClientePort, BancoClienteService.class, features);
    }

}
