
package org.taller.moduloDeTransferencia.wscliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BancoClienteService", targetNamespace = "http://ws.bancoClienteMock.taller.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BancoClienteService {


    /**
     * 
     * @param arg0
     * @return
     *     returns org.taller.moduloDeTransferencia.wscliente.ConfirmationResponse
     */
    @WebMethod(operationName = "NotificarTransferencia")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "NotificarTransferencia", targetNamespace = "http://ws.bancoClienteMock.taller.org/", className = "org.taller.moduloDeTransferencia.wscliente.NotificarTransferencia")
    @ResponseWrapper(localName = "NotificarTransferenciaResponse", targetNamespace = "http://ws.bancoClienteMock.taller.org/", className = "org.taller.moduloDeTransferencia.wscliente.NotificarTransferenciaResponse")
    public ConfirmationResponse notificarTransferencia(
        @WebParam(name = "arg0", targetNamespace = "")
        NotificationRequest arg0);

}
