package org.taller.moduloDeTransferencia.wscliente;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2025-06-11T22:47:23.124-03:00
 * Generated source version: 4.0.0
 *
 */
@WebService(targetNamespace = "http://ws.bancoClienteMock.taller.org/", name = "BancoClienteService")
@XmlSeeAlso({ObjectFactory.class})
public interface BancoClienteService {

    @WebMethod(operationName = "NotificarTransferencia")
    @RequestWrapper(localName = "NotificarTransferencia", targetNamespace = "http://ws.bancoClienteMock.taller.org/", className = "org.taller.moduloDeTransferencia.wscliente.NotificarTransferencia")
    @ResponseWrapper(localName = "NotificarTransferenciaResponse", targetNamespace = "http://ws.bancoClienteMock.taller.org/", className = "org.taller.moduloDeTransferencia.wscliente.NotificarTransferenciaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.taller.moduloDeTransferencia.wscliente.ConfirmationResponse notificarTransferencia(

        @WebParam(name = "arg0", targetNamespace = "")
        org.taller.moduloDeTransferencia.wscliente.NotificationRequest arg0
    );
}
